# Generated by Django 5.1.6 on 2025-02-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='generated_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seed', models.IntegerField(null=True)),
                ('width', models.IntegerField(default=512)),
                ('height', models.IntegerField(default=512)),
                ('num_inference_steps', models.IntegerField(default=50)),
                ('guidance_scale', models.FloatField(default=7.5)),
            ],
        ),
    ]
